name: Deploy to Remote Server

on:
  push:
    branches:
      - main
  workflow_dispatch:    

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2    

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Extract repository name
      id: extract_repo     
      run: echo "repo_name=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)" >> $GITHUB_ENV

    - name: Remove existing directory if it exists
      run: |
        set -x
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          rm -rf ~/workspace/common/${{ env.repo_name  }}
        "

    - name: Create directory
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          mkdir -p ~/workspace/common/${{ env.repo_name }}
        "   

    - name: Copy files to remote server
      run: |
        set -e
        pwd
        ls -l
        scp -r -o StrictHostKeyChecking=no "$(pwd)"/* ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:~/workspace/common/${{ env.repo_name }}

    - name: Deploy with Docker Compose
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "
          cd ~/workspace/common/${{ env.repo_name }} &&          
          export SMTP_USERNAME=${{ secrets.SMTP_USERNAME }} &&          
          export SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }} &&                    
          docker compose build --no-cache && docker compose up -d --force-recreate
        "
